config/routes.rb
Pages::Application.routes.draw do
  get "comments/new"
  get "comments/create"
  get "comments/show"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "home/index"
  root 'home#index'
  resources :ebooks do
collection do
get 'my'
get 'inactive'
get 'lastpaid'
get 'lastfree'
get 'toppaid'
get 'topfree'
end
member do
  get 'download_pdf'
end

end
  resources :comments
  devise_for :users

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :ebook
end

app/models/ebook.rb
class Ebook < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
   has_attached_file :pdfs
  validates_attachment :pdfs, content_type: { content_type: "application/pdf" }

validates :title, :author, presence: true
validates :review, length: {minimum: 150}, allow_blank: true
validates :description, length: {minimum: 50}, presence: true


 belongs_to :user
 before_create :set_downloaded

  has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>", :cropped => "200" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

default_scope -> {order'created_at DESC'}

 self.per_page = 6
 after_validation(on: :create) do
self.active = false
end


def self.search(search)
  if search
    find(:all, :conditions => ['title LIKE ? OR author LIKE ?', "%#{search}%", "%#{search}%"])
  else
    find(:all)
  end
end

scope :active, ->{where active:true}
scope :inactive, ->{where active:false}

scope :pay, ->{where paid:true}
scope :free, ->{where paid:false}


private

  def set_downloaded
    self.downloaded = 0
  end




end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
has_many :ebooks, dependent: :destroy
has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller? 
  protected 
  def configure_permitted_parameters 
  	devise_parameter_sanitizer.for(:sign_up) << :nick 
  	devise_parameter_sanitizer.for(:sign_in) << :nick
  	
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
  end

  def show
  end
end

app/controllers/ebooks_controller.rb
require 'will_paginate/array' 
  class EbooksController < ApplicationController

  before_action :set_ebook, only: [:show, :edit, :update, :destroy,:download_pdf]
  before_action :authenticate_user!, only: [:create,:my]
  before_action :set_update_downloaded, only: [:download_pdf]

  def index
    @ebooks = Ebook.active.paginate(:page => params[:page]).search(params[:search])
  end
  def my
    @ebooks = current_user.ebooks.paginate(:page =>params[:page])
    
  end
  def inactive
    @ebooks = Ebook.inactive.paginate(:page =>params[:page])
    render :index
  end
  def lastpaid
    @ebooks = Ebook.active.pay.last(6).paginate(:page =>params[:page])
    render :index
  end
  def lastfree
    @ebooks = Ebook.active.free.last(6).paginate(:page =>params[:page])
    render :index
  end  
  def home
    @ebooks = Ebook.last(6).paginate(:page =>params[:page])
  end
  def download_pdf
  redirect_to root_url[0..-2] + @ebook.pdfs.url
  end



  def toppaid
    @ebooks = Ebook.active.pay.order(:downloaded).last(6).paginate(:page =>params[:page])
    render :index
  end
  def topfree
    @ebooks = Ebook.active.free.order(:downloaded).last(6).paginate(:page =>params[:page])
    render :index
  end


  # GET /ebooks/1
  # GET /ebooks/1.json
  def show
 end

  # GET /ebooks/new
  def new
    @ebook = Ebook.new
  end

  # GET /ebooks/1/edit
  def edit
  end

  # POST /ebooks
  # POST /ebooks.json
  def create

    @ebook = Ebook.new(ebook_params)
    @ebook.pdfs = params[:ebook][:pdfs]
    
    

    @ebook= current_user.ebooks.new(ebook_params)


    respond_to do |format|
      if @ebook.save
        format.html { redirect_to @ebook, notice: 'Ebook was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ebook }
      else
        format.html { render action: 'new' }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ebooks/1
  # PATCH/PUT /ebooks/1.json
  def update
    respond_to do |format|
      if @ebook.update(ebook_params)
        format.html { redirect_to @ebook, notice: 'Ebook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ebooks/1
  # DELETE /ebooks/1.json
  def destroy
    @ebook.destroy
    respond_to do |format|
      format.html { redirect_to ebooks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ebook
      @ebook = Ebook.find(params[:id])
    end
    def reverse_order
      @ebooks = Ebook.reverse_order
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def ebook_params
      params.require(:ebook).permit(:title, :author, :review, :description, :user_id, :cover, :pdfs)
    end

    def set_update_downloaded
      @ebook.update_attributes(downloaded: @ebook.downloaded+1)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	 @ebooks = Ebook.active.search(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ebooks_helper.rb
module EbooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/_show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/ebooks/_form.html.erb
<%= form_for @ebook, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :cover, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :cover, :class => 'file_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :review, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :review, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field' %>
    </div>
  </div>
 <div class="control-group">

    <%= f.label :pdfs, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :pdfs, :class => 'file_field' %>
    </div>
  </div>
 <div class="control-group">
    <%= f.label :paid, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :paid, :class => 'boolean_field' %>
    </div>
  </div>


   <div class="control-group">
    <%= f.label :cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :cost, :class => 'number_field' %>
    </div>
  </div>



  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ebooks_path, :class => 'btn' %>

  </div>
<% end %>

app/views/ebooks/_home.html.erb
<div class="page-header">
  <h1>Welcome to Pages</h1>
</div>

<dl class="dl-horizontal">

<% @ebooks.each do |ebook| %>
<dd><%= ebook.title %></dd>
<dd><%= ebook.author %></dd>
<dd><%= ebook.review %></dd>
<dd><%=link_to 'Download', ebook_path(ebook)%></dd>
<dd></dd>
<%end%>
</dl>

app/views/ebooks/edit.html.erb
<%- model_class = Ebook -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ebooks/index.html.erb
<ul class ="thumbnails">

<%- model_class = Ebook -%>
 <% @ebooks.each do |ebook| %>
      <li>
      <%= link_to image_tag(ebook.cover.url(:medium)),ebook_path(ebook) %>
       <td><%= link_to ebook.title, :controller => "ebooks", :action => "index", :search => ebook.title %></td>
        <td><%= link_to ebook.author, :controller => "ebooks", :action => "index", :search => ebook.author %></td>

      </li>
    <% end %>
    <%= will_paginate @ebooks %>
  </ul>

app/views/ebooks/my.html.erb
<ul class ="thumbnails">

<%- model_class = Ebook -%>
 <% @ebooks.each do |ebook| %>
      <li>
      <%= link_to image_tag(ebook.cover.url(:medium)),ebook_path(ebook) %>
       <td><%= link_to ebook.title, :controller => "ebooks", :action => "index", :search => ebook.title %></td>
        <td><%= link_to ebook.author, :controller => "ebooks", :action => "index", :search => ebook.author %></td>

      </li>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ebook_path(ebook), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ebook_path(ebook),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
    <% end %>
    <%= will_paginate @ebooks %>
  </ul>

app/views/ebooks/new.html.erb
<%- model_class = Ebook -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ebooks/show.html.erb
<%- model_class = Ebook -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dd><%= image_tag @ebook.cover.url(:medium)%></dd>
</dl>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @ebook.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
  <dd><%= @ebook.author %></dd>
  <dt><strong><%= model_class.human_attribute_name(:review) %>:</strong></dt>
  <dd><%= @ebook.review %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @ebook.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= link_to @ebook.user.nick, my_ebooks_path %></dd>
  <dd><%= link_to 'Download', download_pdf_ebook_path%></dd>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ebooks_path, :class => 'btn'  %>
  
</div>

app/views/home/index.html.erb
<%= render '/ebooks/home'%>

app/views/home/search.html.erb
<h1>search </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pages" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Pages', home_index_path, :class =>"brand" %>
          <div class="container-fluid nav-collapse"> 
            <ul style="float: right" class="nav">
               <li><%= link_to "Ebooks", ebooks_path %></li>
           <li><%= link_to "Top Free", topfree_ebooks_path %></li>
           <li><%= link_to "Top Paid", toppaid_ebooks_path %></li>
           <% if user_signed_in? %>
             
<li><%= link_to "New", new_ebook_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %></li>
            
            
            <%else%>
            <li><%= link_to "Sign up",new_user_registration_path%></li>

            <%end%>
            
            <li><%= form_tag ebooks_path, :method => 'get' do %></li>

    <li><%= text_field_tag :search, params[:search] %></li>
    <li><%= submit_tag "Search"%></li>



<%end%>

          </div><!--/.nav-collapse -->

          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
            
              <li class="nav-header">Profile</li>
              <li><%= link_to "Recent Free", lastfree_ebooks_path %></li>
           <li><%= link_to "Recent Paid", lastpaid_ebooks_path %></li>
              <% if user_signed_in? %>
              <li><%= link_to "Uncommited", inactive_ebooks_path %></li>
              <li><%= link_to "My Ebooks", my_ebooks_path %></li>
              <li><%=link_to 'Account', edit_user_registration_path%></li>
              
              <%else%>

              <li><%= link_to "Login", new_user_session_path %></li>
              <%end%>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>